spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/academy_management_db?currentSchema=academy
    username: adenilson
    password: 356132
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        default_schema: academy

  sql:
    init:
      mode: never

server:
  port: 8080