spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/academy_management_db?currentSchema=academy
    username: adenilson
    password: 356132
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        default_schema: academy

  sql:
    init:
      mode: never

server:
  port: 8081

keycloak:
  server-url: http://localhost:8080
  realm: academy-app
  client-id: academy-app
  client-secret: seu-client-secret
  admin-client-id: admin-cli
  admin-username: adenilson
  admin-password: 356132
